apiVersion: hlf.kungfusoftware.es/v1alpha1
kind: FabricMainChannel
metadata:
  creationTimestamp: "2025-06-04T02:49:05Z"
  finalizers:
  - finalizer.mainChannel.hlf.kungfusoftware.es
  generation: 1
  name: demo
  resourceVersion: "54483"
  uid: 2cd0e6f7-0066-415d-a7af-cb896da850b9
spec:
  adminOrdererOrganizations:
  - mspID: OrdererMSP
  adminPeerOrganizations:
  - mspID: Org1MSP
  channelConfig:
    application:
      acls: null
      capabilities:
      - V2_0
      policies: null
    capabilities:
    - V2_0
    orderer:
      batchSize:
        absoluteMaxBytes: 1048576
        maxMessageCount: 10
        preferredMaxBytes: 524288
      batchTimeout: 2s
      capabilities:
      - V2_0
      consenterMapping: null
      etcdRaft:
        options:
          electionTick: 10
          heartbeatTick: 1
          maxInflightBlocks: 5
          snapshotIntervalSize: 16777216
          tickInterval: 500ms
      ordererType: etcdraft
      policies: null
      smartBFT: null
      state: STATE_NORMAL
    policies: null
  externalOrdererOrganizations: []
  externalPeerOrganizations:
  - mspID: Org1MSP
    signRootCert: |
      -----BEGIN CERTIFICATE-----
      MIICPjCCAeWgAwIBAgIQEYxi7WaNVx8KZQPM6HG+ujAKBggqhkjOPQQDAjBqMQsw
      CQYDVQQGEwJFUzERMA8GA1UEBxMIQWxpY2FudGUxETAPBgNVBAkTCEFsaWNhbnRl
      MRkwFwYDVQQKExBLdW5nIEZ1IFNvZnR3YXJlMQ0wCwYDVQQLEwRUZWNoMQswCQYD
      VQQDEwJjYTAeFw0yNTA2MDMwMjM4MThaFw0zNTA2MDQwMjM4MThaMGoxCzAJBgNV
      BAYTAkVTMREwDwYDVQQHEwhBbGljYW50ZTERMA8GA1UECRMIQWxpY2FudGUxGTAX
      BgNVBAoTEEt1bmcgRnUgU29mdHdhcmUxDTALBgNVBAsTBFRlY2gxCzAJBgNVBAMT
      AmNhMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEpgG0tjjHnX03rLfRo64mZqls
      +Gl6gPNbclc0g+r3adXTV/s5ra119oblNewFj/xjIFrXkHoQ7eVZ2qi1cQ1jqqNt
      MGswDgYDVR0PAQH/BAQDAgGmMB0GA1UdJQQWMBQGCCsGAQUFBwMCBggrBgEFBQcD
      ATAPBgNVHRMBAf8EBTADAQH/MCkGA1UdDgQiBCA9yNIx9OBBpN9IGh5tZng0V+Y4
      DalJ9kTGAuNhvs15WTAKBggqhkjOPQQDAgNHADBEAiBU0kTSDs0XGQINKqJgvCjc
      PFNc6fewyuwAOFRvF9tE7QIgdftdwVvrAsz9gEkE/0CpvQPtT2SosGBA+JRUHx2E
      KM4=
      -----END CERTIFICATE-----
    tlsRootCert: |
      -----BEGIN CERTIFICATE-----
      MIICRzCCAeygAwIBAgIRALbe1TsuPSIaQW9DF+Eq/28wCgYIKoZIzj0EAwIwbTEL
      MAkGA1UEBhMCRVMxETAPBgNVBAcTCEFsaWNhbnRlMREwDwYDVQQJEwhBbGljYW50
      ZTEZMBcGA1UEChMQS3VuZyBGdSBTb2Z0d2FyZTENMAsGA1UECxMEVGVjaDEOMAwG
      A1UEAxMFdGxzY2EwHhcNMjUwNjAzMDIzODE4WhcNMzUwNjA0MDIzODE4WjBtMQsw
      CQYDVQQGEwJFUzERMA8GA1UEBxMIQWxpY2FudGUxETAPBgNVBAkTCEFsaWNhbnRl
      MRkwFwYDVQQKExBLdW5nIEZ1IFNvZnR3YXJlMQ0wCwYDVQQLEwRUZWNoMQ4wDAYD
      VQQDEwV0bHNjYTBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABN7EYAd29kZNc1hX
      e32Kt14NgO/xOiI9NjxN+vqcZKMoDv6cEH1abvBtgpuJN75mY3U6oZ+/iWvB+nO0
      DE+E+2ajbTBrMA4GA1UdDwEB/wQEAwIBpjAdBgNVHSUEFjAUBggrBgEFBQcDAgYI
      KwYBBQUHAwEwDwYDVR0TAQH/BAUwAwEB/zApBgNVHQ4EIgQgagnb02uGatgkkGQt
      obJW+TR8yVJxlHHnKVYEFIxB5LQwCgYIKoZIzj0EAwIDSQAwRgIhALHlZkysogcg
      0MlOEKRQ//JsyEpBWFrXHWV/+mRx+tQoAiEAh5SstOExkxy5n9GHcsG04xCWQhXQ
      /Y/ZVf09LRlQXPk=
      -----END CERTIFICATE-----
  identities:
    OrdererMSP:
      secretKey: orderermsp.yaml
      secretName: wallet
      secretNamespace: default
    OrdererMSP-sign:
      secretKey: orderermspsign.yaml
      secretName: wallet
      secretNamespace: default
    Org1MSP:
      secretKey: org1msp.yaml
      secretName: wallet
      secretNamespace: default
    Org1MSP-tls:
      secretKey: org1msp-tlsca.yaml
      secretName: wallet
      secretNamespace: default
  name: demo
  ordererOrganizations:
  - caName: ""
    caNamespace: ""
    externalOrderersToJoin: []
    mspID: OrdererMSP
    ordererEndpoints:
    - orderer0-ord.localho.st:443
    - orderer1-ord.localho.st:443
    - orderer2-ord.localho.st:443
    - orderer3-ord.localho.st:443
    orderersToJoin:
    - name: ord-node1
      namespace: default
    - name: ord-node2
      namespace: default
    - name: ord-node3
      namespace: default
    - name: ord-node4
      namespace: default
    signCACert: |
      -----BEGIN CERTIFICATE-----
      MIICPjCCAeWgAwIBAgIQEACs7b8XKQ5Q3P4xu3MLeDAKBggqhkjOPQQDAjBqMQsw
      CQYDVQQGEwJFUzERMA8GA1UEBxMIQWxpY2FudGUxETAPBgNVBAkTCEFsaWNhbnRl
      MRkwFwYDVQQKExBLdW5nIEZ1IFNvZnR3YXJlMQ0wCwYDVQQLEwRUZWNoMQswCQYD
      VQQDEwJjYTAeFw0yNTA2MDMwMjM4MThaFw0zNTA2MDQwMjM4MThaMGoxCzAJBgNV
      BAYTAkVTMREwDwYDVQQHEwhBbGljYW50ZTERMA8GA1UECRMIQWxpY2FudGUxGTAX
      BgNVBAoTEEt1bmcgRnUgU29mdHdhcmUxDTALBgNVBAsTBFRlY2gxCzAJBgNVBAMT
      AmNhMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEWY/lRCCOe4FLhw53vKbUls7w
      R8JeL/tnqtwQpRiSazcY1xP3sPAzPdTgw7myuJ+RrpjhK351TZM2FdIiymZuY6Nt
      MGswDgYDVR0PAQH/BAQDAgGmMB0GA1UdJQQWMBQGCCsGAQUFBwMCBggrBgEFBQcD
      ATAPBgNVHRMBAf8EBTADAQH/MCkGA1UdDgQiBCB8MNeNLwj0M9C4rFM7K9lPoNdI
      8d/eBfXETARoEGnZqTAKBggqhkjOPQQDAgNHADBEAiBdMd3DTt4cP/ZcBAj5nhp9
      MRVG/WY1B0vsnYRxFTyBSQIgcoOv6cFM0L9t/lhOwrk5X2lz/ZsgZ0ZyXcfXwR5o
      UEs=
      -----END CERTIFICATE-----
    tlsCACert: |
      -----BEGIN CERTIFICATE-----
      MIICRTCCAeugAwIBAgIQRH1KwShq8/i6vTYa7hMfZDAKBggqhkjOPQQDAjBtMQsw
      CQYDVQQGEwJFUzERMA8GA1UEBxMIQWxpY2FudGUxETAPBgNVBAkTCEFsaWNhbnRl
      MRkwFwYDVQQKExBLdW5nIEZ1IFNvZnR3YXJlMQ0wCwYDVQQLEwRUZWNoMQ4wDAYD
      VQQDEwV0bHNjYTAeFw0yNTA2MDMwMjM4MThaFw0zNTA2MDQwMjM4MThaMG0xCzAJ
      BgNVBAYTAkVTMREwDwYDVQQHEwhBbGljYW50ZTERMA8GA1UECRMIQWxpY2FudGUx
      GTAXBgNVBAoTEEt1bmcgRnUgU29mdHdhcmUxDTALBgNVBAsTBFRlY2gxDjAMBgNV
      BAMTBXRsc2NhMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAE+Kk9d7qRYHcED5b/
      92pLDlvIMzV6opD9J4kqZICjS0R2UYe5GGMCWAZ4qrTS6vy2p8V0oI1bcaDsOW9H
      3kKXm6NtMGswDgYDVR0PAQH/BAQDAgGmMB0GA1UdJQQWMBQGCCsGAQUFBwMCBggr
      BgEFBQcDATAPBgNVHRMBAf8EBTADAQH/MCkGA1UdDgQiBCCBkPlEb+zO4QPRiv9k
      3C1qNdBeBfGmPQ9ytDcEVr43JDAKBggqhkjOPQQDAgNIADBFAiAHmobpvddlOAzw
      f6MMpbxEYca/gmZ78mKrbuBbhByAywIhAKKVRgnWCIVS4dLqvQof4zrEAPROWIA5
      4bhwzRONxZag
      -----END CERTIFICATE-----
  orderers:
  - host: orderer0-ord.localho.st
    port: 443
    tlsCert: |
      -----BEGIN CERTIFICATE-----
      MIIC9zCCAp2gAwIBAgIUJq+MtuJWwBY/R4nrkPU0qB6Lb7UwCgYIKoZIzj0EAwIw
      bTELMAkGA1UEBhMCRVMxETAPBgNVBAcTCEFsaWNhbnRlMREwDwYDVQQJEwhBbGlj
      YW50ZTEZMBcGA1UEChMQS3VuZyBGdSBTb2Z0d2FyZTENMAsGA1UECxMEVGVjaDEO
      MAwGA1UEAxMFdGxzY2EwHhcNMjUwNjAzMDIzODE4WhcNMjYwNjA0MDI0MDAwWjAk
      MRAwDgYDVQQLEwdvcmRlcmVyMRAwDgYDVQQDEwdvcmRlcmVyMFkwEwYHKoZIzj0C
      AQYIKoZIzj0DAQcDQgAEe+U6u4vUs8wjzJ72nTNaHXPfHTYBHR/BucmDE3o+k8u4
      5dg4qrpUeB4WhCaVpyMe35gl1Tnj1mQKfs0IvgWu66OCAWIwggFeMA4GA1UdDwEB
      /wQEAwIDqDAdBgNVHSUEFjAUBggrBgEFBQcDAQYIKwYBBQUHAwIwDAYDVR0TAQH/
      BAIwADAdBgNVHQ4EFgQUR+AMpBIlolXBft87Lb2h1TjDAyQwKwYDVR0jBCQwIoAg
      gZD5RG/szuED0Yr/ZNwtajXQXgXxpj0PcrQ3BFa+NyQwdgYDVR0RBG8wbYIJbG9j
      YWxob3N0gglvcmQtbm9kZTGCEW9yZC1ub2RlMS5kZWZhdWx0ghdvcmRlcmVyMC1v
      cmQubG9jYWxoby5zdIIdYWRtaW4tb3JkZXJlcjAtb3JkLmxvY2FsaG8uc3SHBH8A
      AAGHBDaRzQ4wWwYIKgMEBQYHCAEET3siYXR0cnMiOnsiaGYuQWZmaWxpYXRpb24i
      OiIiLCJoZi5FbnJvbGxtZW50SUQiOiJvcmRlcmVyIiwiaGYuVHlwZSI6Im9yZGVy
      ZXIifX0wCgYIKoZIzj0EAwIDSAAwRQIhANMfjXA+HafatSg5/nVm8NMaKMK8Mz+Y
      ZM9/SQHxQEinAiBiLD/Gs9MWYH/o11e4424tjbJybbYttFDtDk0euyZErg==
      -----END CERTIFICATE-----
  peerOrganizations: []
status:
  conditions:
  - lastTransitionTime: "2025-06-04T02:49:05Z"
    message: 'error saving channel configuration: create channel failed: create channel
      failed: SendEnvelope failed: calling orderer ''orderer3-ord.localho.st:443''
      failed: Orderer Server Status Code: (400) BAD_REQUEST. Description: error applying
      config update to existing channel ''demo'': consensus metadata update for channel
      config update is invalid: update of more than one consenter at a time is not
      supported, requested changes: add 0 node(s), remove 3 node(s)'
    reason: 'error saving channel configuration: create channel failed: create channel
      failed: SendEnvelope failed: calling orderer ''orderer3-ord.localho.st:443''
      failed: Orderer Server Status Code: (400) BAD_REQUEST. Description: error applying
      config update to existing channel ''demo'': consensus metadata update for channel
      config update is invalid: update of more than one consenter at a time is not
      supported, requested changes: add 0 node(s), remove 3 node(s)'
    status: "False"
    type: FAILED
  message: 'error saving channel configuration: create channel failed: create channel
    failed: SendEnvelope failed: calling orderer ''orderer3-ord.localho.st:443'' failed:
    Orderer Server Status Code: (400) BAD_REQUEST. Description: error applying config
    update to existing channel ''demo'': consensus metadata update for channel config
    update is invalid: update of more than one consenter at a time is not supported,
    requested changes: add 0 node(s), remove 3 node(s)'
  status: FAILED